# Overview of what we need to do:

# 1 - When a issue is labeled as 'suggestion', trigger the workflow.
# 2 - Retrieve the github username of the author of the issue
# 3 - Retrieve the issue's facts
# 4 - Parse the facts and put in a nice json format
# 5 - Read facts database
# 6 - Add the new fact(s) to facts database
# 7 - Overwrite facts database
# 8 - Add, commit, push
# 9 - :)

# Each of these steps introduce a new challenge.
# 1 needs a bit of search to know the syntax.
# 2~3 can be solved with env vars, I think.
# 4~7 are pretty much just plain programming,
# but... node or python? I wouldn't like to deal with npm for now.
# 8... authorizing things is tricky...

name: Add new fact
on:
  issues:
    types:
      - labeled
jobs:
  add-new-fact:
    if: github.event.label.name == 'suggestion'
    runs-on: ubuntu-latest
    steps:
      - name: Add new fact
        # uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          run: ls
          body: |
            ls
